# Generated by Django 4.0.4 on 2023-03-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['ID'],
            },
        ),
        migrations.CreateModel(
            name='TNPGuest',
            fields=[
                ('FormID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField()),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('CompanyName', models.CharField(max_length=50)),
                ('HR_PhoneNo', models.CharField(max_length=10)),
                ('HR_Email', models.CharField(max_length=30)),
                ('NoRooms', models.IntegerField()),
                ('NoMales', models.IntegerField()),
                ('NoFemales', models.IntegerField()),
                ('AOCheck', models.BooleanField()),
                ('SupervisorCheck', models.BooleanField()),
                ('VCCheck', models.BooleanField()),
                ('Status', models.BooleanField()),
                ('Comment', models.CharField(max_length=120)),
                ('SentBack', models.BooleanField()),
            ],
            options={
                'ordering': ['FormID'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('RoomID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=20)),
                ('FloorName', models.CharField(max_length=20)),
                ('Capacity', models.IntegerField()),
                ('LastUsedDate', models.DateTimeField()),
                ('Status', models.BooleanField()),
                ('LastOccupant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.tnpguest')),
            ],
            options={
                'ordering': ['RoomID'],
            },
        ),
    ]
